name: Ejecutar script Python

on:
  push:            # Se ejecuta al hacer push
    branches: [ main ]
  pull_request:    # También al hacer PR
    branches: [ main ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias (si tienes un requirements.txt)
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ejecutar el script
      run: python main.py
